
package com.example.demo1.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ChinaZipSearchWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChinaZipSearchWebServiceSoap {


    /**
     * <br /><h3>��ñ����������ѯWeb Services֧�ֵ�ʡ��/ֱϽ����Ϣ</h3><p>����������ޣ� �������ݣ�һ��һά�ַ������� String()������Ϊʡ��/ֱϽ�е����ơ�</p><br />
     *
     * @return
     *     returns com.example.demo1.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportProvince")
    @WebResult(name = "getSupportProvinceResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportProvince", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetSupportProvince")
    @ResponseWrapper(localName = "getSupportProvinceResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetSupportProvinceResponse")
    public ArrayOfString getSupportProvince();

    /**
     * <br /><h3>ͨ��ʡ��/ֱϽ�в�ѯ�����������ѯWeb Services֧�ֵĳ��С�������Ϣ</h3><p>���������byProvinceName = ָ����ʡ��/ֱϽ�У���Ϊ����Ĭ���Ϻ����������ݣ�һ��һά�ַ������� String()���ṹΪ�����С�����(ʡ��/ֱϽ��)��</p><br />
     *
     * @param byProvinceName
     * @return
     *     returns com.example.demo1.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportCity")
    @WebResult(name = "getSupportCityResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportCity", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetSupportCity")
    @ResponseWrapper(localName = "getSupportCityResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetSupportCityResponse")
    public ArrayOfString getSupportCity(
        @WebParam(name = "byProvinceName", targetNamespace = "http://WebXml.com.cn/")
        String byProvinceName);

    /**
     * <br /><h3>��ñ����������ѯWeb Services֧�ֵ�ȫ��ʡ��/ֱϽ�� �� ���С�������Ϣ</h3><p>����������գ��������ݣ�DataSet���ṹΪ��Item.(CITY)=���С�������Item.(PROVINCE)=ʡ��/ֱϽ�С�</p><br />
     *
     * @return
     *     returns com.example.demo1.webxml.GetSupportProvinceCityResponse.GetSupportProvinceCityResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportProvinceCity")
    @WebResult(name = "getSupportProvinceCityResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportProvinceCity", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetSupportProvinceCity")
    @ResponseWrapper(localName = "getSupportProvinceCityResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetSupportProvinceCityResponse")
    public GetSupportProvinceCityResponse.GetSupportProvinceCityResult getSupportProvinceCity();

    /**
     * <br /><h3>ͨ�����������ѯ�����������ѯWeb Services֧�ֵ�ַ����</h3><p>���������theZipCode = �й���6λ�������룬��Ϊ����Ĭ���Ϻ�200080��userID = ��ҵ�û�ID����ͨ�û�����Ҫ�����������ݣ�DataSet���ṹΪ��Item.(ADDRESS)=�ֵ�������Item.(CITY)=���С�������Item.(PROVINCE)=ʡ��/ֱϽ�У�Item.(ZIP)=�������롣</p><br />
     *
     * @param userID
     * @param theZipCode
     * @return
     *     returns com.example.demo1.webxml.GetAddressByZipCodeResponse.GetAddressByZipCodeResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getAddressByZipCode")
    @WebResult(name = "getAddressByZipCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getAddressByZipCode", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetAddressByZipCode")
    @ResponseWrapper(localName = "getAddressByZipCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetAddressByZipCodeResponse")
    public GetAddressByZipCodeResponse.GetAddressByZipCodeResult getAddressByZipCode(
        @WebParam(name = "theZipCode", targetNamespace = "http://WebXml.com.cn/")
        String theZipCode,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

    /**
     * <br /><h3>ͨ��ʡ�ݡ����С���ַ��ѯ�����������ѯWeb Services֧��������������</h3><p>���������theProvinceName = ʡ��/ֱϽ�У����밴�� getSupportProvince ���룩��theCityName = ���С�������theAddress = �ֵ�������userID = ��ҵ�û�ID����ͨ�û�����Ҫ����theProvinceName��Ϊ����Ĭ���Ϻ���֧��ģ����ѯ������û�������20��������ݣ�������ʾ������<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">��ϵ����</a>�����������ݣ�DataSet���ṹΪ��Item.(ADDRESS)=�ֵ�������Item.(CITY)=���С�������Item.(PROVINCE)=ʡ��/ֱϽ�У�Item.(ZIP)=�������롣</p><br />
     *
     * @param theCityName
     * @param theAddress
     * @param userID
     * @param theProvinceName
     * @return
     *     returns com.example.demo1.webxml.GetZipCodeByAddressResponse.GetZipCodeByAddressResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getZipCodeByAddress")
    @WebResult(name = "getZipCodeByAddressResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getZipCodeByAddress", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetZipCodeByAddress")
    @ResponseWrapper(localName = "getZipCodeByAddressResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.example.demo1.webxml.GetZipCodeByAddressResponse")
    public GetZipCodeByAddressResponse.GetZipCodeByAddressResult getZipCodeByAddress(
        @WebParam(name = "theProvinceName", targetNamespace = "http://WebXml.com.cn/")
        String theProvinceName,
        @WebParam(name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
        String theCityName,
        @WebParam(name = "theAddress", targetNamespace = "http://WebXml.com.cn/")
        String theAddress,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

}
