
package com.example.demo1.webxml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>�й������������� WEB ����</strong>�����й�ȫ���������빲��187285����¼����Ŀǰ�������������������ݣ���ȷ�����򼶡����о�ȷ���ֵ���֧����������<->���С����򡢽ֵ���˫���ѯ�������������ѯ�����ο���������������ַ�б䶯���Ե����ʾ�Ϊ׼��Ҳ�뼰ʱ<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">֪ͨ����</a>���и�����<br />�����������ѯWeb Services�벻Ҫ�����κ���ҵĿ�ģ�������Ҫ��<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">��ϵ����</a>����ӭ���������� QQ��8409035<br /><strong>ʹ�ñ�վ WEB ������ע�������ӱ�վ��http://www.webxml.com.cn/ ��л��ҵ�֧��</strong>��<br /><br />&nbsp;
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ChinaZipSearchWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/D:/swpu/Science/\u8f6f\u4ef6\u4f53\u7cfb\u7ed3\u6784/demo1/src/main/java/com/example/demo1/ZipSearch.wsdl")
public class ChinaZipSearchWebService
    extends Service
{

    private final static URL CHINAZIPSEARCHWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHINAZIPSEARCHWEBSERVICE_EXCEPTION;
    private final static QName CHINAZIPSEARCHWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "ChinaZipSearchWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/swpu/Science/\u8f6f\u4ef6\u4f53\u7cfb\u7ed3\u6784/demo1/src/main/java/com/example/demo1/ZipSearch.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHINAZIPSEARCHWEBSERVICE_WSDL_LOCATION = url;
        CHINAZIPSEARCHWEBSERVICE_EXCEPTION = e;
    }

    public ChinaZipSearchWebService() {
        super(__getWsdlLocation(), CHINAZIPSEARCHWEBSERVICE_QNAME);
    }

    public ChinaZipSearchWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHINAZIPSEARCHWEBSERVICE_QNAME, features);
    }

    public ChinaZipSearchWebService(URL wsdlLocation) {
        super(wsdlLocation, CHINAZIPSEARCHWEBSERVICE_QNAME);
    }

    public ChinaZipSearchWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHINAZIPSEARCHWEBSERVICE_QNAME, features);
    }

    public ChinaZipSearchWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChinaZipSearchWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ChinaZipSearchWebServiceSoap
     */
    @WebEndpoint(name = "ChinaZipSearchWebServiceSoap")
    public ChinaZipSearchWebServiceSoap getChinaZipSearchWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaZipSearchWebServiceSoap"), ChinaZipSearchWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaZipSearchWebServiceSoap
     */
    @WebEndpoint(name = "ChinaZipSearchWebServiceSoap")
    public ChinaZipSearchWebServiceSoap getChinaZipSearchWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaZipSearchWebServiceSoap"), ChinaZipSearchWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHINAZIPSEARCHWEBSERVICE_EXCEPTION!= null) {
            throw CHINAZIPSEARCHWEBSERVICE_EXCEPTION;
        }
        return CHINAZIPSEARCHWEBSERVICE_WSDL_LOCATION;
    }

}
